### PR TITLE
Document -r/--rev for git-push-to-try

### PR DESCRIPTION
**Pull request by fitzgen**

### CODE REVIEW

**Comment by jlebar** [comment]
I think @Nephyrin or maybe @ehsan ?  Not me anymore, though I'm happy to see people are still using this stuff.

**Comment by jryans** [comment]
@amccreight will likely take a look soon, I think!

**Comment by fitzgen** [comment]
ping @amccreight

**Comment by amccreight** [comment]
Weird, I don't know why I didn't get a notification for this before now.

**Comment by amccreight** [comment]
Thanks for the patch.

**Comment by amccreight** [comment]
Oh, I do see a notification in my mail trash.  I somehow managed to delete it without noticing it.  Sorry about that!

**Pull request merged**
